# Subject Analysis
### This notebook will explore 3 subjects and their associated records

In [ ]:
import pandas as pd
from joblib import load
import os

:

In [ ]:
directory = '/work/mbouthil/Research_Project/MIMIC-III_data/MIMIC-III_demo'
os.chdir(directory)

df = pd.read("Demo_Master_Dataframe.joblib")

In [75]:
# Altering column values to integer (categorical) or float objects
count = 0
for col, col_values in df.items():
    if df[col].dtype == ('O'):
        df[col] = df[col].astype('category').cat.codes
       
    if df[col].dtype == ('<m8[ns]'):
        df[col] = df[col].dt.total_seconds()
        df[col] = df[col]/(60**2*24)
    
    count += 1
    if count == 13:
        break

df['ed_duration'] = df['ed_duration'].clip(lower=0)
df = df[df['age'] <= 100]
df = df[df['age'] >= 1]
df = df[df['los'] <= 30]
df = df[df['admit_duration'] <= 30]
df = df[df['ed_duration'] <= 1]
df['ed_duration'] = df['ed_duration'].clip(lower=0)

display(df.head(10))

,subject_id,admission_type,admission_location,discharge_location,insurance,marital_status,ethnicity,read_flag,admit_duration,ed_duration,gender,los,age,inputs,events,labs,prescriptions,procedures
0,42231,0,2,2,1,0,7,0.0,8.378472,0.000000,0,1.1358,86,itemid amount 10574 225828 16.6...,itemid value cg...,itemid valuenum 59437 50800 0.0...,drug d...,itemid cgid duration 570 224275...
1,43881,1,1,2,2,0,7,1.0,5.948611,0.279861,1,1.9252,53,itemid amount 868 225154 1.000...,itemid value cgid 6817 2...,itemid valuenum 69528 51221 23.3...,dru...,itemid cgid duration 47 224275 ...
2,43879,1,0,1,1,0,2,0.0,0.980556,0.000000,0,0.9775,55,itemid amount 10853 225825 361.0...,itemid value cgi...,itemid valuenum 68752 50868 12.0...,drug dose_val_rx 627...,itemid cgid duration 618 224275...
3,10088,1,1,8,1,1,7,1.0,7.156944,0.160417,1,3.6885,78,itemid amount 747 30013 50.000 ...,itemid value cgid 1808 40055 ...,itemid valuenum 16910 50861 1....,drug dose_va...,"Empty DataFrame Columns: [itemid, cgid, durati..."
4,10061,1,3,7,1,1,7,0.0,24.997917,0.000000,0,24.9968,76,itemid amount 19 30056 0.0 20...,itemid value cgid 486 40055 ...,itemid valuenum 11156 50862 3.0...,drug dos...,"Empty DataFrame Columns: [itemid, cgid, durati..."
5,44083,1,1,2,2,1,7,1.0,2.911806,0.318750,1,2.1026,55,itemid amount 7771 225158 49.999...,itemid value cgid...,itemid valuenum 71424 50862 3....,drug...,itemid cgid duration 458 224275...
6,42199,1,1,8,1,0,7,0.0,9.968750,0.373611,0,5.4263,73,itemid amount 7452 223262 2.0...,itemid value cgid 8764 226...,itemid valuenum 59087 50910 52.0...,drug dose_val_rx...,itemid cgid duration 391 224275...
7,10119,1,1,7,1,0,7,1.0,13.908333,0.318056,1,7.9020,81,itemid amount 1027 30013 500.0...,itemid value cgid 3539 40292 1...,itemid valuenum 25594 50800 0.0...,drug...,"Empty DataFrame Columns: [itemid, cgid, durati..."
8,40456,1,1,1,1,1,7,0.0,2.878472,0.143056,0,2.0003,87,itemid amount 935 226452 400.00000...,itemid value cgid 6831 ...,itemid valuenum 46252 50800 0.0...,drug dose_val...,itemid cgid duration 51 224275 ...
9,10104,1,1,8,1,0,1,0.0,6.814583,0.349306,0,0.6628,70,itemid amount 137 30056 360.0 138 ...,itemid value cgid 1765 40055 ...,itemid valuenum 20878 50868 17....,drug dose_val_rx...,"Empty DataFrame Columns: [itemid, cgid, durati..."

In [76]:
subject_id = 10104

In [77]:
def subject_to_csv(subject_id): 

    '''This function will save all related subjcet_id
    information for the provided subject_id'''

    # Gathering rows
    inputs = df.loc[df['subject_id'] == subject_id, 'inputs'].iloc[0]
    events = df.loc[df['subject_id'] == subject_id, 'events'].iloc[0]
    labs = df.loc[df['subject_id'] == subject_id, 'labs'].iloc[0]
    prescriptions = df.loc[df['subject_id'] == subject_id, 'prescriptions'].iloc[0]
    procedures = df.loc[df['subject_id'] == subject_id, 'procedures'].iloc[0]
    row = df.loc[df['subject_id'] == subject_id].drop(labels=['inputs', 'events', 'labs', 'prescriptions', 'procedures'],
                                                      axis = 1)
    # Saving .csv files
    inputs.to_csv('subject_inputs.csv', index=False)
    events.to_csv('subject_events.csv', index=False)
    labs.to_csv('subject_labs.csv', index=False)
    prescriptions.to_csv('subject_prescriptions.csv', index=False)
    procedures.to_csv('subject_procedures.csv', index=False)
    row.to_csv('Subject_row.csv', index=False)

    display(prescriptions)

In [78]:
subject_to_csv(subject_id)

                              drug dose_val_rx
693              Ampicillin Sodium           1
694                    Ceftriaxone           1
695              Magnesium Sulfate           4
696            Potassium Phosphate          15
697        Hydrocortisone Na Succ.          50
698    Sodium Chloride 0.9%  Flush           3
699                      Metformin         500
700           Levothyroxine Sodium          75
701                   Atorvastatin          40
702                      Vitamin D         400
703                      Bisacodyl          10
704                      Bisacodyl          10
705  Fluticasone Propionate 110mcg           2
706              Calcium Carbonate         500
707                  Acetaminophen     325-650
708                        Heparin        5000
709                     Famotidine          20
710                          Senna           1
711                Docusate Sodium         100
712                      Lactulose          30
713               Artificial Tears         1-2
714             Alendronate Sodium          70
715                  Dexamethasone           4
716             Albuterol Neb Soln           1
717                        Insulin           0
718             Potassium Chloride          40
719                     Prednisone          10
720                  Levetiracetam         500
721    Sodium Chloride 0.9%  Flush           3
722              Calcium Gluconate           2
723              Calcium Gluconate           2
724                  Levetiracetam         250
725                     Zonisamide          50
726                     Prednisone          10
727                Sodium Chloride           1
728                     Ampicillin         500
729                      Lactulose         300
730                     Zonisamide         100
731              Calcium Carbonate         500
732             Tuberculin Protein         0.1
733                      Lactulose        1000
734                Sodium Chloride           2
735                      Metformin         500
736                      Lactulose         300
737                      Lactulose          30
738                    Mineral Oil          30
739                     Cephalexin         500
740           Estrogens Conjugated           1
741                      Lactulose         300
742   Nitrofurantoin (Macrodantin)          50
743                 Hydrocortisone          15
744                 Hydrocortisone          10
745                             NS          50
746           Iso-Osmotic Dextrose          50
747                             NS         250
748                            D5W         250
749                        Syringe           1