# Development Script

Jan 14th, 2026

Maxime Bouthillier

### University of Waterloo - MMATH CM Research Project

In [1]:
# Importing packages
import pandas as pd
import torch
import os
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
from huggingface_hub import login
from transformers import AutoTokenizer, AutoModelForCausalLM, logging, AutoModel
logging.set_verbosity_error()
import random
import re
import numpy as np
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm
from typing import List
from dotenv import load_dotenv
import os
from torch import Tensor

In [2]:
# Loading token
load_dotenv('token.env')
token = os.getenv('HUGGINGFACE_TOKEN')

# Loading model - pass token directly
model_name = "meta-llama/Llama-3.1-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, token=token)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.bfloat16,
    device_map="auto",
    token=token  # Pass token here
)

In [4]:
# Loading Note Events dataset
df = pd.read_csv("/work/mbouthil/projects/physionet.org/files/mimiciii/1.4/NOTEEVENTS.csv.gz", nrows=1000)
df = df[['SUBJECT_ID', 'TEXT']]
notes = df['TEXT'].tolist()

# Exploring Notes:

## Note Splitting

### Chunking based on headers

In [188]:
note = df['TEXT'].iloc[3]

def detail_merge(sections:list[str], min_words:int=10):
    merged = ['Details:']

    for section in sections:
        word_count = len(section.split())

        if word_count < min_words:
            merged[0] = merged[0] + "\n" + section
        
        else:
            merged.append(section)

    return merged


def header_split(note: str, min_words:int=10) -> list[str]:
    pattern = r'(?:^|\n)([A-Za-z][A-Za-z ]{3,50}):\s*(.*?)(?=(?:\n[A-Za-z][A-Za-z ]{3,50}:)|$)'
    matches = re.findall(pattern, note, flags=re.DOTALL)

    if not matches:
        return [note]

    # Reconstruct header + content
    sections = [f"{h}: {c}".strip() for h, c in matches if c.strip()]
    sections = [" ".join([word for word in section.split(' ') if word]) for section in sections]

    sections = detail_merge(sections, min_words)
    

    return sections

note = header_split(note)

In [87]:
def paragraph_splits(note:str) -> list[str]:

    paragraphs = re.split(r"\n\s*\n\n+", note)
    return [p.strip() for p in paragraphs if p.strip()]

In [95]:
splits = paragraph_splits(note)

for i in splits:
    print(i)
    print('END')

Admission Date:  [**2119-5-4**]              Discharge Date:   [**2119-5-25**]
END
Service: CARDIOTHORACIC

Allergies:
Amlodipine

Attending:[**Last Name (NamePattern1) 1561**]
Chief Complaint:
81 yo F smoker w/ COPD, severe TBM, s/p tracheobronchoplasty [**5-5**]
s/p perc trach [**5-13**]

Major Surgical or Invasive Procedure:
bronchoscopy 3/31,4/2,3,[**6-12**], [**5-17**], [**5-19**]
s/p trachealplasty [**5-5**]
percutaneous tracheostomy [**5-13**] after failed extubation
down size trach on [**5-25**] to size 6 cuffless
END
History of Present Illness:
This 81 year old woman has a history of COPD. Over the past five

years she has had progressive difficulties with her breathing.
In
[**2118-6-4**] she was admitted to [**Hospital1 18**] for respiratory failure
due
to a COPD exacerbation. Due to persistent hypoxemia, she
required
intubation and a eventual bronchoscopy on [**2118-6-9**] revealed marked

narrowing of the airways on expiration consistent with
tracheomalacia.
She subsequently underwent placement of two
silicone stents, one in the left main stem and one in the
trachea. During the admission the patient had complaints of
chest
pain and ruled out for an MI. She was subsequently discharged to

[**Hospital1 **] for physical and pulmonary rehab. Repeat bronchoscopy
on
[**2118-8-1**] revealed granulation tissue at the distal right lateral
wall of the tracheal stent. There was significant malacia of the

peripheral and central airways with complete collapse of the
airways on coughing and forced expiration. Small nodules were
also noted on the vocal cords. She has noticed improvement in
her
respiratory status, but most recently has been in discussion
with Dr. [**First Name4 (NamePattern1) 951**] [**Last Name (NamePattern1) 952**] regarding possible tracheobronchial plasty

with mesh. Tracheal stents d/c [**2119-4-19**] in anticipation of
surgery.
In terms of symptoms, she describes many years of intermittent
chest pain that she describes as left sided and occurring at any

time. Currently, she notices it about three times a week, and
states that it seems to resolve after three nitroglycerin.
She currently is dependent on oxygen and wears 1.5-2 liters
around the clock. She has frequent coughing and brings up "dark
sputum".
END
Past Medical History:
COPD flare [**6-7**] s/p intubation, s/p distal tracheal to Left Main
Stem stents placed [**2118-6-9**]. Stents d/c'd [**2119-4-19**], CAD w/ atypical
angina (LAD 30%, RCA 30%, EF 63%), ^chol, hypothyroidism, htn,
hiatal hernia, lacunar CVA, s/p ped struck -> head injury & rib
fx, depression
PMH:
COPD, s/p admit [**6-7**] for exacerbation requiring intubation
tracheobronchomalacia, s/p bronchial stenting
Large hiatal hernia
Lacunar CVA
Hypothyroidism by records in CCC, although patient denies and is

not taking any medication
Depression
MVA, s/p head injury approximately 10 years ago
Hypertension
Hysterectomy
END
Social History:
Social History: The patient is married and worked as a clinical
psychologist. Her husband is a pediatric neurologist at
[**Hospital3 **]. They have several children, one of which is

a nurse.
END
Family History:
Family History: (+) FHx CAD; Father with an MI in his 40's, died

of a CVA at age 59
END
Physical Exam:
Admit H+P
General-lovely 81 yr old feamle in NAD.
Neuro- intermittently anxious, MAE, PERRLA, L eye ptosis,
symetrical smile, gossly intact.
HEENT-PERRLA, sclera anicteric, pharynx- no exud or erythema
Resp-clear upper, diffuse ronchi, intermit exp wheezes
Cor- RRR, No M, R, G
Abd- soft, NT, ND, no masses. Slight protrusion at area of
hiatal hernia
Ext- no edema or clubbing

Brief Hospital Course:
82 y/o female admitted [**2119-5-4**] for consideration of
tracheoplasty.
Bronchoscopy done [**5-4**] confirming severe TBM. Underwent
tracheoplasty [**5-5**], complicated by resp failure d/t mucous
plugging, hypoxia requiring re-intubation resulting in prolonged
ICU and hospital course. Also developed right upper extrem DVT
from mid line.

Pain- Epidural accidently d/c'd POD#1, pt briefly used dilaudid
PCA intermittently w/ fair pain control. Pt required
re-intubation for resp failure d/t secretions and PCA d/c at
that time. Propofol for sedation while intubated. Sedation d/c'd
[**5-12**] for weaning trial w/ ETT- failed trial. Trach [**5-13**]-weaning
efforts as below. Minimal c/o pain since [**5-13**]. Presently pain
free.

Neuro- Initially intact- post op aggitation, inhibiting weaning
efforts [**5-16**]. Psych eval [**5-18**]-Started on zyprexa and ativan w/
improvement in anxiety. Presently A+Ox3- cooperative and lovely.

Resp- Extubated POD#2 then required re-intub  [**5-7**] for hypoxia
d/t poor cough and mucous plugging. SIMV/PS alt w/CMV at night
x4-5d, with CPAP attempts during day.
Bronchoscopy qd [**Date range (1) 1813**] for secretion management. Bronch [**5-9**]
revealed swollen epiglottis, bronch [**5-10**] - good leak w/ ETT cuff
deflated. Bronch [**5-13**] for eval/trach placement. Last bronch [**5-19**]
w/ min secretions present, sputum sent.
[**5-13**] perc trach done(#8 Portex- cuffed low pressure maintained to
preserve tracheoplasty site). [**5-13**] CPAP15/peep5 initiated post
trach placement. Weaning ongoing.  [**Date range (1) 1814**]- Aggressive weaning
w/ increasing episodes of CPAP, progressing to Trach Mask.
[**2033-5-20**]-Trach mask overnight w/ no episodes of SOB, or
hemodynamic instability. Trach changed to #6 portex- capped and
[**Last Name (un) 1815**] well x48hrs on 2LNP. productive cough. Aggressive PT as
well w/ OOB > chair [**Hospital1 **]-tid to total 4-6hr qd. Ambulation
~100-120 ft [**5-22**] w/ PT assist.

ID- Vancomycin started post-op for graft prophylaxis. Fever
spike [**2119-5-8**] w/ BAl & sputum sent> + MRSA. Vanco cont to [**4-7**]
weeks post trachealplasty. Fever low grade [**5-12**], [**5-15**]> cultured-
no new results. [**5-19**]- WBC 20.8 .

Cardiac-Hypertension controlled w/ hydralazine IV, then d/c and
cont controlled. HR 65-75 NSR. Avoiding B Blockers. Lasix 20mg
IV qd.
[**5-15**]- RUE redness and swelling at site of midline, RUE DVT by
ultrasound, midline d/c; heparin gtt started and therapeutic
range monitored. [**5-22**]  changed to Lovenox sq [**Hospital1 **]. Coags in good
control [**5-23**] (48.2/13.8/1.2)
Access- R midline placed [**2119-5-9**] for access- clotted [**2119-5-15**] and
d/c'd.  RUE redness and swelling and DVT via ultrasound. [**5-15**]- L
brachial PICC line placed- TPN resumed.

GI-Large hiatal hernia- unable to place enteral feeding tube at
bedside or underfluoro. Re-attempt [**5-17**] by EGD doboff tube
placed distal esophagus, dislodged in 12hours and removed.

Nutrition- PPN/TPN initiated [**2119-5-8**]- [**2119-5-25**]. PICC placed
[**2119-5-15**]. Speech and Swallow eval [**5-22**]- rec change trach form #8
to #6 Portex to allow improved epiglotis and oropharyngeal
movement to assist w/ swallowing. Then re-eval.  Trach changed
[**5-23**] to #6 cuffless portex trach. Passed repeat swallow eval and
[**Last Name (un) 1815**] diet of regular solids w/ thin liquids- CHIN TUCK to
swallow thin liquids. Give meds whole w/ apple sauce. WOULD
RECOMMEND repeat video swallow eval in [**8-17**] days to possibly
eliminate chin tuck- see page 3 referral.

Endo- Hypothyroid, maintained on levoxyl.

Muscu/Skel- OOB> chair 4-6hours/day, PT consulting.
END
Medications on Admission:
advair 250/50", atrovent, imdur 60', lasix 40', lexapro 20',
lipitor 10', prilosec 20', mucinex 600", synthroid 75', detrol
LA 4', ambien 5', trazadone 75', melatonin prn

Discharge Medications:
1. Albuterol Sulfate 0.083 % Solution Sig: One (1)  Inhalation
Q6H (every 6 hours) as needed for wheezing.
2. Ipratropium Bromide 0.02 % Solution Sig: One (1)  Inhalation
Q6H (every 6 hours) as needed for wheezing.
3. Fluticasone-Salmeterol 250-50 mcg/Dose Disk with Device Sig:
One (1) Disk with Device Inhalation [**Hospital1 **] (2 times a day).
4. Albuterol 90 mcg/Actuation Aerosol Sig: 1-2 Puffs Inhalation
Q6H (every 6 hours) as needed.
5. Ipratropium Bromide 18 mcg/Actuation Aerosol Sig: Two (2)
Puff Inhalation QID (4 times a day).
6. Acetaminophen 325 mg Tablet Sig: 1-2 Tablets PO Q4-6H (every
4 to 6 hours) as needed.
7. Sodium Chloride 0.65 % Aerosol, Spray Sig: [**2-5**] Sprays Nasal
QID (4 times a day) as needed.
8. Camphor-Menthol 0.5-0.5 % Lotion Sig: One (1) Appl Topical
TID (3 times a day) as needed.
9. Enoxaparin Sodium 60 mg/0.6mL Syringe Sig: One (1)
Subcutaneous Q12H (every 12 hours).
10. Trazodone HCl 50 mg Tablet Sig: 1.5 Tablets PO HS (at
bedtime) as needed.
11. Escitalopram Oxalate 10 mg Tablet Sig: Two (2) Tablet PO
DAILY (Daily).
12. Nystatin 100,000 unit/g Cream Sig: One (1) Appl Topical  [**Hospital1 **]
(2 times a day).
13. Pantoprazole Sodium 40 mg Tablet, Delayed Release (E.C.)
Sig: One (1) Tablet, Delayed Release (E.C.) PO Q24H (every 24
hours).
14. Tolterodine Tartrate 2 mg Tablet Sig: One (1) Tablet PO BID
(2 times a day).
15. Levothyroxine Sodium 75 mcg Tablet Sig: One (1) Tablet PO
DAILY (Daily).
16. Heparin Lock Flush (Porcine) 100 unit/mL Syringe Sig: One
(1) ML Intravenous  DAILY (Daily) as needed.
END
Discharge Disposition:
Extended Care

Facility:
[**Hospital3 7**] & Rehab Center - [**Hospital1 8**]

Discharge Diagnosis:
COPD, Coronary Artery Disease/atypical angina (LAD 30%, RCA 30%,
EF 63%), hypercholesterolemia, hypothyroidism, Hypertension,
hiatal hernia, Cerebral Vascular Accident,s/p Motor Vehicle
Colision-> head injury & rib fracture.
TBM- s/p tracheoplasty.
END
Discharge Condition:
good

Discharge Instructions:
please update Dr.[**Name (NI) 1816**] [**Telephone/Fax (1) 170**] office for:  fever,
shortness of breath, chest pain , productive cough or if you
have any questions or concerns.
END
Completed by:[**2119-5-25**]
END

### Chunking regarless of content:

In [ ]:
def chunk_by_sentence(text: str, max_chars: int=400) -> list[str]:
    
    """
    Split text into chunks of at most max_chars characters,
    preserving sentence boundaries.

    Parameters
    ----------
    text : str
        Input text to be chunked.
    max_chars : int
        Target maximum character length per chunk.

    Returns
    -------
    List[str]
        List of text chunks.
    """

    # 1. Split text into sentences (keeps punctuation)
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())

    chunks = []
    current_chunk = ""

    for sentence in sentences:
        # Edge case: single sentence longer than max_chars
        if len(sentence) > max_chars:
            if current_chunk:
                chunks.append(current_chunk.strip())
                current_chunk = ""
            chunks.append(sentence.strip())
            continue

        # Try to append sentence to current chunk
        if len(current_chunk) + len(sentence) + 1 <= max_chars:
            current_chunk += (" " if current_chunk else "") + sentence
        else:
            chunks.append(current_chunk.strip())
            current_chunk = sentence

    if current_chunk:
        chunks.append(current_chunk.strip())

    return chunks

In [225]:
splits = chunk_by_sentence(df['TEXT'].iloc[3], 400)

In [226]:
print(len(splits))

45

# Additional Synthetic Query Generation

In [24]:
# Loading Query Passage Dataset
df = pd.read_csv('/work/mbouthil/projects/research_project/MEDRAG/processed_data/synq.csv')
df = df.drop(columns=["TEXT", "NOTE"])

In [25]:
queries = ['Subject ID: ' + str(df['SUBJECT_ID'].iloc[i]) + '\n'  + str(df['QUERY'].iloc[i]) for i in range(len(df))]
passages = ['Subject ID: ' + str(df['SUBJECT_ID'].iloc[i]) + '\n'  + str(df['PASSAGE'].iloc[i]) for i in range(len(df))]

In [83]:
query_test = [query[18:] for query in queries[:2]]
print(query_test)

['Does the patient have a history of tuberculosis prior to this admission?', 'Has the patient had any previous imaging studies or medical evaluations for osteoporosis prior to this current assessmen']

In [14]:
system_prompt = '''
You are a helpful AI Assistant. You will be provided a question written by a doctor.

Your task is to rewrite this question 7 different ways. However, it is crucial that these alternative questions ask the same
underlying question as the provided question.
Feel free to use more or less medical terminology and medical acronyms where you see fit. 
Moreover, keep the questions relatively simple and straight forward. 

Format your output as follows:

**Query_1**

**Query_2**

...

**Query_7** 
'''

In [ ]:
def llm_batch(notes: list[str], system_prompt:str) -> list[str]:
    messages = [
        [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": note}
        ]
        for note in notes
    ]

    prompts = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )

    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.1,
            top_p=0.9,
            do_sample=True
        )

    responses = []
    for i in range(len(notes)):
        gen = outputs[i][inputs["input_ids"].shape[1]:]
        responses.append(tokenizer.decode(gen, skip_special_tokens=True))

    return responses

def chunked(iterable, batch_size):
    for i in range(0, len(iterable), batch_size):
        yield iterable[i:i + batch_size]

In [84]:
add_queries = llm_1(query_test, system_prompt)

In [85]:
def queries_split(queries:list[str]) -> list[list[str]]:

    queries = [re.split(r"\*\*Query_\d+\*\*\s*", query)[1:] for query in queries]
    queries = [[query.replace('/n', '').strip() for query in query_list if query.replace('/n', '').strip()] for query_list in queries]
    return queries

split_queries = queries_split(add_queries)

In [86]:
def df_expansion(df:pd.DataFrame, add_queries:list[list[str]]) -> pd.DataFrame:

    new_df = pd.DataFrame(columns=df.columns)

    for i in range(len(df)):
        queries = add_queries[i]
        row = df.iloc[[i]]

        duplicates = pd.concat([row] * len(queries), ignore_index=True)
        duplicates.loc[:, "QUERY"] = queries

        new_rows = pd.concat([row, duplicates], ignore_index=True)
        new_df = pd.concat([new_df, new_rows], ignore_index=True)

    return new_df

In [87]:
test_df = pd.concat([df.iloc[[0]], df.iloc[[1]]], ignore_index=True)
test_df

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,QUERY,PASSAGE
0,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Does the patient have a history of tuberculosi...,Admission Date: [**2151-7-16**] Dischar...
1,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Has the patient had any previous imaging studi...,HEAD CT: Head CT showed no intracranial hemor...

In [88]:
test_df = df_expansion(test_df, split_queries)

In [89]:
test_df

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,QUERY,PASSAGE
0,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Does the patient have a history of tuberculosi...,Admission Date: [**2151-7-16**] Dischar...
1,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Does the patient have a past medical history o...,Admission Date: [**2151-7-16**] Dischar...
2,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Has the patient ever been diagnosed with tuber...,Admission Date: [**2151-7-16**] Dischar...
3,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Is there a history of tuberculosis in the pati...,Admission Date: [**2151-7-16**] Dischar...
4,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Was tuberculosis a pre-existing condition for ...,Admission Date: [**2151-7-16**] Dischar...
5,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Does the patient have a known history of tuber...,Admission Date: [**2151-7-16**] Dischar...
6,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Is tuberculosis a part of the patient's past m...,Admission Date: [**2151-7-16**] Dischar...
7,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Has the patient previously been treated for tu...,Admission Date: [**2151-7-16**] Dischar...
8,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Has the patient had any previous imaging studi...,HEAD CT: Head CT showed no intracranial hemor...
9,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Has the patient undergone any prior imaging st...,HEAD CT: Head CT showed no intracranial hemor...
10,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Are there any previous imaging studies or medi...,HEAD CT: Head CT showed no intracranial hemor...
11,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Does the patient have a history of osteoporosi...,HEAD CT: Head CT showed no intracranial hemor...
12,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,What is the patient's history of previous imag...,HEAD CT: Head CT showed no intracranial hemor...
13,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Has the patient had any prior osteoporosis-rel...,HEAD CT: Head CT showed no intracranial hemor...
14,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Are there any existing imaging studies or medi...,HEAD CT: Head CT showed no intracranial hemor...
15,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Does the patient have a prior medical history ...,HEAD CT: Head CT showed no intracranial hemor...

### Testing outputs

In [7]:
test_df = pd.read_csv("/work/mbouthil/projects/research_project/MEDRAG/synthetic_data/add_synq.csv")
test_df.head(10)

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,TEXT,NOTE,QUERY,PASSAGE
0,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Does the patient have a history of tuberculosi...,Admission Date: [**2151-7-16**] Dischar...
1,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Does the patient have a past medical history o...,Admission Date: [**2151-7-16**] Dischar...
2,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Is there any prior history of tuberculosis in ...,Admission Date: [**2151-7-16**] Dischar...
3,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Has the patient ever been diagnosed with tuber...,Admission Date: [**2151-7-16**] Dischar...
4,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Is tuberculosis a part of the patient's past m...,Admission Date: [**2151-7-16**] Dischar...
5,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Does the patient have a known history of tuber...,Admission Date: [**2151-7-16**] Dischar...
6,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Is there any documented history of tuberculosi...,Admission Date: [**2151-7-16**] Dischar...
7,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,Admission Date: [**2151-7-16**] Dischar...,Has the patient ever had a diagnosis of tuberc...,Admission Date: [**2151-7-16**] Dischar...
8,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,HEAD CT: Head CT showed no intracranial hemor...,Has the patient had any previous imaging studi...,HEAD CT: Head CT showed no intracranial hemor...
9,174,22532,167853,2151-08-04,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2151-7-16**] Dischar...,HEAD CT: Head CT showed no intracranial hemor...,Has the patient undergone any prior imaging st...,HEAD CT: Head CT showed no intracranial hemor...

# Testing the trained Retreiver

In [3]:
df = pd.read_csv("/work/mbouthil/projects/research_project/MEDRAG/processed_data/synq.csv")
passages = ['Subject ID: ' + str(df['SUBJECT_ID'].iloc[i]) + '\n'  + str(df['PASSAGE'].iloc[i]) for i in range(len(df))]
queries = ['Subject ID: ' + str(df['SUBJECT_ID'].iloc[i]) + '\n'  + str(df['QUERY'].iloc[i]) for i in range(len(df))]

In [100]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
passage_encoder = AutoModel.from_pretrained("bert-base-uncased")

passage_encoder = AutoModel.from_pretrained(
    "/work/mbouthil/projects/research_project/MEDRAG/model_weights/passage_encoder"
) # .to("cuda")

passage_encoder.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

In [ ]:
def encode_passage(notes:list[str], batch_size:int=32) -> Tensor:

    embeddings = []

    with torch.no_grad():
        for i in range(0, len(notes), batch_size):
            batch = notes[i:i+batch_size]

            inputs = tokenizer(
                batch, 
                padding=True,
                truncation=True,
                return_tensors="pt",
                max_length=512
            ) #.to("cuda")

        outputs = passage_encoder(**inputs)
        cls_embeddings = outputs.last_hidden_state[:, 0] 

        embeddings.append(cls_embeddings.cpu())

    return torch.cat(embeddings, 0)

In [119]:
test_passages = passages
embeddings = encode_passage(test_passages)

KeyboardInterrupt:

In [7]:
len(synq)

28431

# Actual Retrieval

In [20]:
import faiss 
import json

In [21]:
# Loading embeddings and confirming shape
embeddings_np = np.load("/work/mbouthil/projects/research_project/MEDRAG/retrieval_data/passage_embeddings.npy")
embeddings_np.shape

(28431, 768)

In [22]:
# Loading Index
index = faiss.read_index("/work/mbouthil/projects/research_project/MEDRAG/retrieval_data/passage.index")

# Load metadata
metadata = []
with open("/work/mbouthil/projects/research_project/MEDRAG/retrieval_data/passage_metadata.jsonl") as f:
    for line in f:
        metadata.append(json.loads(line))

In [23]:
# Loading Query Encoder
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
query_encoder = AutoModel.from_pretrained("bert-base-uncased")

query_encoder = AutoModel.from_pretrained(
    "/work/mbouthil/projects/research_project/MEDRAG/model_weights/query_encoder"
) # .to("cuda")

query_encoder.eval()

def encode_query(query:str, batch_size:int=32) -> Tensor:

    embeddings = []

    with torch.no_grad():
        inputs = tokenizer(
            query, 
            padding=True,
            truncation=True,
            return_tensors="pt",
            max_length=512
        ) #.to("cuda")

    outputs = query_encoder(**inputs)
    cls_embeddings = outputs.last_hidden_state[:, 0] 

    embeddings.append(cls_embeddings.cpu())

    return torch.cat(embeddings, 0)

In [28]:
print(queries[0])
print("/n/n")
print(passages[0])

Subject ID: 22532
Does the patient have a history of tuberculosis prior to this admission?
/n/n
Subject ID: 22532
Admission Date:  [**2151-7-16**]       Discharge Date:  [**2151-8-4**]


Service:
ADDENDUM:

RADIOLOGIC STUDIES:  Radiologic studies also included a chest
CT, which confirmed cavitary lesions in the left lung apex
consistent with infectious process/tuberculosis. This also
moderate-sized left pleural effusion.

In [25]:
query = "Subject ID: 22532\nHas the patient had teberculosis?"
query_emb = encode_query([query]).detach().cpu().numpy()

In [26]:
K = 20
scores, ids = index.search(query_emb, K)

In [31]:
print(scores)

[[278.67456 278.33157 277.29712 276.59564 275.72748 275.01962 274.72366
  274.43604 274.25043 274.155   274.0747  273.98962 273.84848 273.5051
  272.88623 272.64194 272.63574 272.4034  272.3411  272.23718]]

In [37]:
candidates = [metadata[i]["text"] for i in ids[0]]
for i in candidates:
    if "22532" in i:
        print(i)
    print("\n\n")

## Skipping Re-ranker

In [169]:
load_dotenv('token.env')
token = os.getenv('HUGGINGFACE_TOKEN')

# Loading model - pass token directly
model_name = "meta-llama/Llama-3.1-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name, token=token)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    dtype=torch.bfloat16,
    device_map="auto",
    token=token  # Pass token here
)

In [170]:
system_prompt = '''
You are a helpful AI Assistant. 

Use the following provided context to asnwer the question. 
If the answer is not contained within the context, only return "No information found".
'''

note = f'''
Context: {candidates[0]}
Question: {query}

Answer:
'''

messages = [{"role": "system", "content": system_prompt},
            {"role": "user", "content": note}]

In [175]:
prompts = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )

inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True
    ).to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=256,
        temperature=0.1,
        top_p=0.9,
        do_sample=True
    )

input_len = inputs["input_ids"].shape[1]
gen_tokens = outputs[0, input_len:]

response = tokenizer.decode(gen_tokens, skip_special_tokens=True)

In [178]:
print(response[11:].replace("/n", ''))

Yes, the patient has been confirmed to have cavitary lesions in the left lung apex consistent with an infectious process/tuberculosis.

# Additinoal Synthetic Query Trouble Shooting

In [5]:
# Loading in Synthetic Query dataset
df = pd.read_csv('/work/mbouthil/projects/research_project/MEDRAG/synthetic_data/add_synq.csv')

In [7]:
len(df)

800